### PR TITLE
Don't run LBMs every time a mapblock loads

### PR DESCRIPTION
**Pull request by ClobberXD**
Pretty trivial, ready for review.

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
:-1: for now. See #dev in Discord

**Comment by ClobberXD** [comment]
Then this mod is broken and should be disabled until fixed.

I did mention that this LBMs is set to run on every load in the PR page itself, but for some reason I didn't factor it in while approving the PR. >.<

**Comment by rubenwardy** [comment]
This pr won't work as the same locations are used for each map. You'd need to change the map spawn locations to vary more than by map id

**Comment by ClobberXD** [comment]
PR invalidated by https://github.com/MT-CTF/seasonal_xmas/commit/a97b965f47d2ab4a67de39cab9786e22c3b83406

**Pull request closed without merging**
